### ISSUE TITLE
Remove ignoring errors

### ISSUE THREAD

**Issue by egorsmkv** [stil/xpath-selector#1]
Why not give this task a programmer?

``` php
libxml_use_internal_errors(true);
```

**Comment by stil** [comment]
Even if you set `libxml_use_internal_errors(true);`, it still throws warnings to standard output.
`@` operator prevents PHP from printing warnings, but you can still handle parse errors.

What stops you from doing this?

``` php
use XPathSelector\Selector;

libxml_use_internal_errors(true);
$selector = Selector::loadHTMLFile("http://www.wikipedia.org/");

foreach (libxml_get_errors() as $error) {
    // handle errors here
}
libxml_clear_errors();
```

**Comment by egorsmkv** [comment]
I do not need to suppress errors in the library. Maybe do the treatment without ignoring errors?

**Comment by stil** [comment]
Have you read the code in previous comment? It shows you a way to handle errors. They're not ignored, you can still detect and process them.

**Comment by egorsmkv** [comment]
Thus removing here "@"?

``` php
    public static function loadHTMLFile($html)
    {
        $dom = new DOMDocument();
        @$dom->loadHTMLFile($html);
        return new self($dom);
    }
```

**Comment by stil** [comment]
Why do you need to remove @?
You can handle libxml errors even when it's still here. @ just prevents from printing warnings to standard output by default.

**Comment by egorsmkv** [comment]
I'm saying I do not need to be so.
All error handling should be my concern.

**Comment by stil** [comment]
I'm sorry, I can't fix it for you. It would cause problems with backward compatibility. And I think, that printing PHP warnings is not the best way to cope with errors. If you need to handle errors, you can use `libxml_get_errors()` function.
